services:
  listenbrainz-docker:
    image: ghcr.io/2t0m/listenbrainz-docker:latest
    container_name: listenbrainz-docker
    volumes:
      - /mnt/usbhdd/music:/app/music
    environment:
      LOG_LEVEL: "DEBUG"
      LISTENBRAINZ_URL: "https://listenbrainz.org/syndication-feed/user/YOUR_USERNAME/recommendations?recommendation_type=weekly-exploration"
      LISTENBRAINZ_M3U_FILENAME: "@Created for You.m3u8"
      LISTENBRAINZ_BASE_PATH: "/app/music"
      DEEMIX_ARL: "YOUR_ARL_HERE"
      SYNC_INTERVAL: 86400
    restart: always
