services:
  listenbrainz-docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listenbrainz-docker
    volumes:
      - /mnt/usbhdd/music:/app/music  # Mount the local music directory to /app/music in the container
    environment:
      LOG_LEVEL: "DEBUG"  # Logging level for the application (e.g., DEBUG, INFO, WARNING, ERROR)

      # Environment variables for listenbrainz_sync.py
      LISTENBRAINZ_RUN_ONCE: "True"  # Run the playlist synchronization script immediately at container startup
      LISTENBRAINZ_CRON_ENABLED: "True"  # Enable scheduled execution via cron
      LISTENBRAINZ_CRON_SCHEDULE: "30 1 * * *"  # Cron schedule for running the script (default: every 30 minutes)
      LISTENBRAINZ_URL: "https://listenbrainz.org/syndication-feed/user/YOUR_USERNAME/recommendations?recommendation_type=weekly-exploration"
      LISTENBRAINZ_M3U_FILENAME: "@Created for You.m3u8"
      LISTENBRAINZ_BASE_PATH: "/app/music"  # Base path for playlist files

      # ARL for deemix
      DEEMIX_ARL: "YOUR_ARL_HERE"  # Replace with your actual ARL value

    entrypoint: ["/app/entrypoint.sh"]  # Entrypoint script to set up cron and start the application
    restart: always